# -*- coding: utf-8 -*-
"""2A-IR-DL-regression-linear.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cnSTr3a4Lzz-kukdoXHav19Pk680iXyG

authors: [Ali Ismail-Fawaz](https://hadifawaz1999.github.io/) and [Germain Forestier](https://germain-forestier.info/)

# **Gradient Descent**

Import packages used
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

import tensorflow as tf

"""## Downloading the dataset"""

#!wget https://hadifawaz1999.github.io/teaching/Ensisa/2A-Info/DeepLearning/datasets/pokemon-stats-data.csv

"""## Reading the data"""

df = pd.read_csv("pokemon-stats-data.csv")

df = df.dropna()
df.head()

"""## Extract the features to be used"""

X = np.asarray(df[["weight_kg","sp_attack"]], dtype=np.float32)
Y = np.asarray(df["sp_defense"], dtype=np.float32)

print("Number of samples in the dataset is "+str(len(X)))

"""## Split the dataset into train and test sets"""

xtrain, xtest, ytrain, ytest = train_test_split(X, Y, test_size=33/100, random_state=42)

print("Number of training examples is "+str(len(xtrain)))
print("Number of testing examples is "+str(len(xtest)))

"""## Normalize the dataset"""

xtrain = MinMaxScaler().fit_transform(xtrain)
xtest = MinMaxScaler().fit_transform(xtest)

"""## Create using Tensorflow-Keras a linear model

### Create an input layer with the same shape as one example in xtrain
"""

input_shape = xtrain.shape[1:]

input_layer = tf.keras.layers.Input(input_shape)

"""### Create an output layer containing one unit (neuron) with linear activation that takes as input the `input_layer` just created"""

output_layer = tf.keras.layers.Dense(units=1, activation="linear")(input_layer)

"""### Create the model (a perceptron)"""

model = tf.keras.models.Model(inputs=input_layer, outputs=output_layer)

model.summary()

"""### Choose the optimiazation algorithm and set the learning rate to $0.1$"""

learning_rate = 0.1
optimizer_algo = tf.keras.optimizers.SGD(learning_rate=learning_rate)

"""### Choose the cost function to optimize: `Mean Squared Error`"""

cost_function = tf.keras.losses.mse

"""### Compile the model"""

model.compile(loss=cost_function, optimizer=optimizer_algo)

"""### Train the model with a `batch size` of $32$ for $100$ epochs"""

mini_batch_size = 64
nb_epochs = 500

tf.random.set_seed(42)

history = model.fit(xtrain,
                    ytrain,
                    batch_size=mini_batch_size,
                    epochs=nb_epochs,
                    verbose=0,)

"""### Plot the error changing with each epoch on the training set"""

history_dict = history.history
loss_epochs = history_dict["loss"]

plt.figure()
plt.plot(loss_epochs)
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.show()
plt.close()

"""### Evaluate the model on the train set"""

loss_train = model.evaluate(xtrain, ytrain, verbose=False)
print("The error on the train set is = "+str(loss_train))

"""## Plot the predictions in the case of a plane

### Plot the training data without the predictions
"""

fig = plt.figure()

plot3d = fig.add_subplot(111, projection="3d")

ax = plt.gca()

ax.view_init(elev=10, azim=20)

plot3d.scatter(xtrain[:,0], xtrain[:,1], ytrain)

ax.set_xlabel("Weight (x1)")
ax.set_ylabel("Attack (x2)")
ax.set_zlabel("Defense (y)")

plt.show()
plt.close()

"""### Recover the learned parameters"""

learned_parameters = model.layers[-1].get_weights()

w = learned_parameters[0]
b = learned_parameters[1]

print("w = "+str(w))
print("b = "+str(b))

"""### Plot the decision plane"""

x1_min = xtrain[:,0].min()
x1_max = xtrain[:,0].max()
x2_min = xtrain[:,1].min()
x2_max = xtrain[:,1].max()

nb_points_plane = 100

x1 = np.linspace(start=x1_min, stop=x1_max, num=nb_points_plane)
x1 = x1.reshape(-1,1)
x2 = np.linspace(start=x2_min, stop=x2_max, num=nb_points_plane)
x2 = x2.reshape(-1,1)

X = np.concatenate((x1,x2), axis=1)
ypred = model.predict(X)

Xmesh1, Xmesh2 = np.meshgrid(x1, x2)

for angle in range(59, 180, 30):
  fig = plt.figure()
  plot3d = fig.add_subplot(111, projection="3d")
  ax = plt.gca()

  ax.set_xlabel("Weight (x1)")
  ax.set_ylabel("Attack (x2)")
  ax.set_zlabel("Defense (y)")

  ax.view_init(elev=10, azim=angle)

  plot3d.scatter(xtrain[:,0], xtrain[:,1], ytrain)
  plot3d.plot_surface(Xmesh1, Xmesh2, ypred, color="green", rstride=100, cstride=100, alpha=0.5, edgecolor='black')

"""# **Exercise**

## Evaluate on the test set
"""



"""## Plot the predicted defense values with respect to the true values of the test set"""



"""## Train a model while taking 2 attributes (weight and speed) and a non-linear relationship between these 2 attributes"""



"""## Plot the predicted values with respect to the real values of the test set"""

