# -*- coding: utf-8 -*-
"""DeepLearning2AIR_MLP_exercise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ys1-pPnM69469VjO6HsCLPWx_zpLeeXe

# Multi-Layer Perceptron (MLP) exercise
author : [Maxime Devanne](https://www.maxime-devanne.com)

## Importing libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.utils import to_categorical

"""## Downloading the dataset of Pokemon images"""

# !wget 'https://www.maxime-devanne.com/datasets/Pokemon_images/X_train_hr.npy'
# !wget 'https://www.maxime-devanne.com/datasets/Pokemon_images/y_train_hr.npy'
# !wget 'https://www.maxime-devanne.com/datasets/Pokemon_images/X_test_hr.npy'
# !wget 'https://www.maxime-devanne.com/datasets/Pokemon_images/y_test_hr.npy'

"""## Loading and preparing data"""

# load data
X_train = np.load('X_train_hr.npy')
y_train = np.load('y_train_hr.npy')
X_test = np.load('X_test_hr.npy')
y_test = np.load('y_test_hr.npy')

# get information about image dimensions
width = int(X_train.shape[1])
height = int(X_train.shape[2])
n_channels = int(X_train.shape[3])

"""Image visualization"""

id=8
plt.imshow(X_train[id])
plt.axis('off')
print(y_train[id])

"""Reshape the image into a 1D vector of pixels"""

X_train = X_train.reshape((X_train.shape[0],X_train.shape[1]*X_train.shape[2]*X_train.shape[3]))
print(X_train.shape)

"""Transforming labels into "one-hot" vectors"""

y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

"""## Exercise

1. Build the following MLP:
*   Input data : an image of a pokemon
*   Two hidden layers of 512 neurons each, with ReLU activation
*   A final output layer for classification with 12 neurons (nb. of classes)
2. Train the MLP on the training set:
*   On 1000 epochs
*   Using a batch size of 16
*   Using the Adam optimizer
3. Evaluate the trained MLP on the test set
"""

#lets start
input_shape = (width*height*n_channels,)
model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=input_shape),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(12, activation='softmax')
])
model.summary()
model.compile(optimizer=tf.keras.optimizers.Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
history = model.fit(X_train, y_train, epochs=1000, batch_size=16, verbose=True)
loss, acc = model.evaluate(X_test, y_test)
print("L'accuracy sur l'ensemble du test est:",acc)