# -*- coding: utf-8 -*-
"""DeepLearning2AIR_Regularization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ZddIfcpPA9K44t8sKcqHJjElCLgUaZd

Authors: [Maxime Devanne](https://maxime-devanne.com), [Germain Forestier](https://germain-forestier.info/), [Hassan Ismail Fawaz](https://hfawaz.github.io) and [Jonathan Weber](http://jonathan-weber.eu/)

# Regularization in Neural Networks

## Import modules
"""

import os

from pandas import pd

from sklearn.preprocessing import normalize
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
import random
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist
from tensorflow.keras.datasets import fashion_mnist
from tensorflow.keras.utils import to_categorical

"""##MNIST dataset

### Load MNIST dataset
"""

(x_train, y_train), (x_test, y_test) = mnist.load_data()

# reduce size of train to speedup the training
nnn=1000
x_train = x_train[:nnn]
y_train = y_train[:nnn]

print("x_train",x_train.shape)
print("Number of images for train:",x_train.shape[0])
print("Number of images for test:",x_test.shape[0])
print("Size of an image:",x_train.shape[1:],"which makes:",
      x_train.shape[1]*x_train.shape[2],"pixels")
print("List of classes:",np.unique(y_train))

"""### View some images specifying that it is black and white"""

plt.subplot(221)
plt.imshow(x_train[0], cmap=plt.get_cmap('gray'))
plt.subplot(222)
plt.imshow(x_train[1], cmap=plt.get_cmap('gray'))
plt.subplot(223)
plt.imshow(x_train[2], cmap=plt.get_cmap('gray'))
plt.subplot(224)
plt.imshow(x_train[3], cmap=plt.get_cmap('gray'))
# show the plot
plt.show()

"""### Normalize the data so that each pixel is between 0 and 1"""

# divide by 255 so everything is in [0;1]
x_train = x_train/255
x_test = x_test/255

"""### Transform classes into binary representation(one-hot encoding)"""

y_train_binary = to_categorical(y_train)
y_test_binary = to_categorical(y_test)

"""### Transform the shape of the images (add an empty dimension to say that we have only one channel - gray instead of three for RGB like color images)"""

print(x_train.shape)
x_train = x_train.reshape(x_train.shape[0],x_train.shape[1],x_train.shape[2],1)
print(x_train.shape)
# same for test set
x_test = x_test.reshape(x_test.shape[0],x_test.shape[1],x_test.shape[2],1)

"""## First original CNN model

### Building a new convolutional model with two layers and a softmax classifier as output
"""

# input layer
input_shape = x_train.shape[1:]
input_layer = keras.layers.Input(input_shape)

# convolutional layer 1
hidden_conv_layer_1 = keras.layers.Conv2D(filters=10,
                                          kernel_size=(5,5) ,strides=1,
                                          padding='valid',activation='relu')(input_layer)
# max pooling
hidden_pooling_layer_1 = keras.layers.MaxPooling2D(pool_size=(2,2),strides=2,
                                                  padding='valid')(hidden_conv_layer_1)

# convolution layer 2
hidden_conv_layer_2 = keras.layers.Conv2D(filters=20,
                                          kernel_size=(5,5) ,strides=1,
                                          padding='valid', activation='relu')(hidden_pooling_layer_1)

# max pooling
hidden_pooling_layer_2 = keras.layers.MaxPooling2D(pool_size=(2,2),strides=2,
                                            padding='valid')(hidden_conv_layer_2)

# flatten
flatenned_layer_2 = keras.layers.Flatten()(hidden_pooling_layer_2)

nb_classes= len(np.unique(y_train))

# output layer
output_layer = keras.layers.Dense(units=nb_classes,activation='softmax')(flatenned_layer_2)

# a model linking input and output
model_mnist = keras.models.Model(inputs=input_layer, outputs=output_layer)

# optimization algorithm
optimizer_algo = keras.optimizers.SGD(learning_rate=0.1)

# loss function
cost_function = keras.losses.categorical_crossentropy

# model compilation
model_mnist.compile(loss=cost_function,optimizer=optimizer_algo, metrics=['accuracy'])

# model visualization
model_mnist.summary()

"""### Run model training and plot curves"""

mini_batch_size = 32
nb_epochs = 200

percentage_of_train_as_validation = 0.2
history = model_mnist.fit(x_train,y_train_binary,batch_size=mini_batch_size,
                    epochs=nb_epochs,verbose=False,
                    validation_split=percentage_of_train_as_validation)

history_dict = history.history
loss_train_epochs = history_dict['loss']
loss_val_epochs = history_dict['val_loss']

plt.figure()
plt.plot(loss_train_epochs,color='blue',label='train_loss')
plt.plot(loss_val_epochs,color='red',label='val_loss')
plt.xlabel('epoch')
plt.ylabel('loss')
plt.legend()
plt.savefig('epoch-loss.pdf')
plt.show()
plt.close()

"""### Evaluate the model on the test set"""

loss,acc = model_mnist.evaluate(x_test,y_test_binary,verbose=False)

print("Accuracy on the test set is:",acc)

"""## Explicit Regularization

### Weights Decay

#### Building the same model with a L2 regularization in the second convolutional layer
"""

# input layer
input_shape = x_train.shape[1:]
input_layer = keras.layers.Input(input_shape)

# convolutional layer 1
hidden_conv_layer_1 = keras.layers.Conv2D(filters=10,
                                          kernel_size=(5,5) ,strides=1,
                                          padding='valid',activation='relu')(input_layer)
# max pooling
hidden_pooling_layer_1 = keras.layers.MaxPooling2D(pool_size=(2,2),strides=2,
                                                  padding='valid')(hidden_conv_layer_1)

# convolutional layer 2 with a L2 regulizer
hidden_conv_layer_2 = keras.layers.Conv2D(filters=20,
                                          kernel_size=(5,5) ,strides=1,
                                          padding='valid', activation='relu',kernel_regularizer=keras.regularizers.l2(0.001))(hidden_pooling_layer_1)

# max pooling
hidden_pooling_layer_2 = keras.layers.MaxPooling2D(pool_size=(2,2),strides=2,
                                            padding='valid')(hidden_conv_layer_2)

# flatten
flatenned_layer_2 = keras.layers.Flatten()(hidden_pooling_layer_2)

nb_classes= len(np.unique(y_train))

# output layer
output_layer = keras.layers.Dense(units=nb_classes,activation='softmax')(flatenned_layer_2)

# model linking input and output
model_mnist_wd = keras.models.Model(inputs=input_layer, outputs=output_layer)

# optimization algorithm
optimizer_algo = keras.optimizers.SGD(learning_rate=0.1)

# loss function
cost_function = keras.losses.categorical_crossentropy

# model compilation
model_mnist_wd.compile(loss=cost_function,optimizer=optimizer_algo, metrics=['accuracy'])

# model visualization
model_mnist_wd.summary()

"""#### Run model training and plot curves"""

mini_batch_size = 32
nb_epochs = 200

percentage_of_train_as_validation = 0.3
history = model_mnist_wd.fit(x_train,y_train_binary,batch_size=mini_batch_size,
                    epochs=nb_epochs,verbose=False,
                    validation_split=percentage_of_train_as_validation)

history_dict = history.history
loss_train_epochs = history_dict['loss']
loss_val_epochs = history_dict['val_loss']

plt.figure()
plt.plot(loss_train_epochs,color='blue',label='train_loss')
plt.plot(loss_val_epochs,color='red',label='val_loss')
plt.xlabel('epoch')
plt.ylabel('loss')
plt.legend()
plt.savefig('epoch-loss.pdf')
plt.show()
plt.close()

"""#### Evaluate the model on the test set"""

loss,acc = model_mnist_wd.evaluate(x_test,y_test_binary,verbose=False)

print("Accuracy on the test set is:",acc)

"""### Dropout

#### Same model with a Dropout
"""

# input layer
input_shape = x_train.shape[1:]
input_layer = keras.layers.Input(input_shape)

# convolutional layer 1
hidden_conv_layer_1 = keras.layers.Conv2D(filters=10,
                                          kernel_size=(5,5) ,strides=1,
                                          padding='valid',activation='relu')(input_layer)
# max pooling
hidden_pooling_layer_1 = keras.layers.MaxPooling2D(pool_size=(2,2),strides=2,
                                                  padding='valid')(hidden_conv_layer_1)

# convolutional layer 2 with a L2 regulizer
hidden_conv_layer_2 = keras.layers.Conv2D(filters=20,
                                          kernel_size=(5,5) ,strides=1,
                                          padding='valid', activation='relu',kernel_regularizer=keras.regularizers.l2(0.01))(hidden_pooling_layer_1)

# max pooling
hidden_pooling_layer_2 = keras.layers.MaxPooling2D(pool_size=(2,2),strides=2,
                                            padding='valid')(hidden_conv_layer_2)

# dropout layer
dropout_layer_2 = keras.layers.Dropout(rate=0.5)(hidden_pooling_layer_2)

# flatten
flatenned_layer_2 = keras.layers.Flatten()(dropout_layer_2)

nb_classes= len(np.unique(y_train))

# output layer
output_layer = keras.layers.Dense(units=nb_classes,activation='softmax')(flatenned_layer_2)

# model linking input and output
model_mnist_wd_dropout = keras.models.Model(inputs=input_layer, outputs=output_layer)

# optimization algorithm
optimizer_algo = keras.optimizers.SGD(learning_rate=0.1)

# loss function
cost_function = keras.losses.categorical_crossentropy

# model compilation
model_mnist_wd_dropout.compile(loss=cost_function,optimizer=optimizer_algo, metrics=['accuracy'])

# model visualization
model_mnist_wd_dropout.summary()

"""#### Run model training and plot curves"""

mini_batch_size = 32
nb_epochs = 200

percentage_of_train_as_validation = 0.2
history = model_mnist_wd_dropout.fit(x_train,y_train_binary,batch_size=mini_batch_size,
                    epochs=nb_epochs,verbose=False,
                    validation_split=percentage_of_train_as_validation)

history_dict = history.history
loss_train_epochs = history_dict['loss']
loss_val_epochs = history_dict['val_loss']

plt.figure()
plt.plot(loss_train_epochs,color='blue',label='train_loss')
plt.plot(loss_val_epochs,color='red',label='val_loss')
plt.xlabel('epoch')
plt.ylabel('loss')
plt.legend()
plt.savefig('epoch-loss.pdf')
plt.show()
plt.close()

"""#### Evaluate the model on the test set"""

loss,acc = model_mnist_wd_dropout.evaluate(x_test,y_test_binary,verbose=False)

print("Accuracy on the test set is:",acc)

"""### Data augmentation

#### Define a generator which takes a data set as input and returns its augmentation
"""

# use Keras datagenerator
datagen = keras.preprocessing.image.ImageDataGenerator(featurewise_center=True,
                                                       featurewise_std_normalization=True,
                                                       rotation_range=20, # random rotation angle
                                                       width_shift_range=0.1, #  horizontal shifting
                                                       height_shift_range = 0.1, # vertical shifting
                                                      )

"""#### Test the augmentation on 9 images to see"""

for i in range(0, 9):
	plt.subplot(330 + 1 + i)
	plt.imshow(x_train[i,:,:,0], cmap=plt.get_cmap('gray'))
# show the plot
plt.show()

# give the data to augment
datagen.fit(x_train,augment=True)

# iterate on online data augmentation
for x_batch, y_batch in datagen.flow(x_train,y_train,batch_size = 9,shuffle=False):
  # trace the one that has undergone a random modification
  for i in range(9):
    plt.subplot(330+1+i)
    plt.imshow(x_batch[i,:,:,0], cmap=plt.get_cmap('gray'))
  plt.show()
  plt.close()
  break

x_train_augmented_list = []
x_train_augmented_list.append(x_train)
y_train_augmented_list = []
y_train_augmented_list.append(y_train_binary)
for x_batch,y_batch in datagen.flow(x_train,y_train,batch_size=400):
  x_train_augmented_list.append(x_batch)
  y_batch_binary = to_categorical(y_batch)
  y_train_augmented_list.append(y_batch_binary)
  if len(x_train_augmented_list)>=5:
    break
x_train_augmented = np.concatenate(x_train_augmented_list)
y_train_augmented = np.concatenate(y_train_augmented_list)
print(x_train_augmented.shape)
print(y_train_augmented.shape)

"""### Create a two-layer convolutional model with the softmax classifier output
For seeing how to add an implicit regularization, we add a Batch normalization layer after the convolutional layers
"""

# Create input layer
input_shape = x_train.shape[1:]
input_layer = keras.layers.Input(input_shape)

# Create convolutive layer
hidden_conv_layer_1 = keras.layers.Conv2D(filters=16,
                                          kernel_size=(5,5) ,strides=1,
                                          padding='valid',activation='relu')(input_layer)
# create second convolutive layer
hidden_conv_layer_2 = keras.layers.Conv2D(filters=8,
                                          kernel_size=(5,5) ,strides=1,
                                          padding='valid')(hidden_conv_layer_1)

# add a batch normalization layer before activation
batch_norm_layer_2 = keras.layers.BatchNormalization(axis=-1)(hidden_conv_layer_2)

# add activation reread
activation_layer_2 = keras.layers.Activation('relu')(batch_norm_layer_2)

# flatten the image
flatenned_layer_2 = keras.layers.Flatten()(activation_layer_2)

nb_classes= len(np.unique(y_train))

# create the output layer
output_layer = keras.layers.Dense(units=nb_classes,activation='softmax')(flatenned_layer_2)

# create the model by linking the input to the output
model_mnist_bn = keras.models.Model(inputs=input_layer, outputs=output_layer)

# visualize the model built
model_mnist_bn.summary()

"""**Why do we have 16 non-trainable parameters?**

### Train the model with the data augmentation
"""

# choose the optimization algorithm
optimizer_algo = keras.optimizers.SGD(learning_rate=0.1)

# cost function that we want to optimize
cost_function = keras.losses.categorical_crossentropy

# compil model
model_mnist_bn.compile(loss=cost_function,optimizer=optimizer_algo, metrics=['accuracy'])

# mini batch size and number of epochs
mini_batch_size = 32
nb_epochs = 200

percentage_of_train_as_validation = 0.2
history = model_mnist_bn.fit(x_train_augmented,y_train_augmented,batch_size=mini_batch_size,
                    epochs=nb_epochs,verbose=False,
                    validation_split=percentage_of_train_as_validation)

history_dict = history.history
loss_train_epochs = history_dict['loss']
loss_val_epochs = history_dict['val_loss']

plt.figure()
plt.plot(loss_train_epochs,color='blue',label='train_loss')
plt.plot(loss_val_epochs,color='red',label='val_loss')
plt.xlabel('epoch')
plt.ylabel('loss')
plt.legend()
plt.savefig('epoch-loss.pdf')
plt.show()
plt.close()

"""### Evaluate on MNIST"""

loss,acc = model_mnist_bn.evaluate(x_test,y_test_binary,verbose=False)

print("Accuracy on test :",acc)

"""## Transfer learning

### Download a pre-trained model like VGG (example)

####  Using this [link](https://keras.io/applications)

In this session we are not going to use a downloaded model as they are usually quite expensive to train, but the example below shows you that it is very easy to retrieve a pre-trained model.
"""

model_vgg = keras.applications.vgg16.VGG16(include_top=True, weights='imagenet', input_tensor=None, input_shape=None, pooling=None, classes=1000)

"""#### Show information about this model"""

model_vgg.summary()

"""### Fashion_MNIST dataset

Instead, we will explore how to use transfer learning of a simpler model between the Fashion MNIST dataset and the digit MNIST dataset
"""

(x_train_fashion, y_train_fashion), (x_test_fashion, y_test_fashion) = fashion_mnist.load_data()

x_train_fashion = x_train_fashion[:1000]
y_train_fashion = y_train_fashion[:1000]

"""#### Show examples of the new dataset"""

plt.subplot(221)
plt.imshow(x_train_fashion[0], cmap=plt.get_cmap('gray'))
plt.subplot(222)
plt.imshow(x_train_fashion[1], cmap=plt.get_cmap('gray'))
plt.subplot(223)
plt.imshow(x_train_fashion[2], cmap=plt.get_cmap('gray'))
plt.subplot(224)
plt.imshow(x_train_fashion[3], cmap=plt.get_cmap('gray'))
# show the plot
plt.show()

"""#### Normalize the data so that each pixel is between 0 and 1"""

x_train_fashion = x_train_fashion/255
x_test_fashion = x_test_fashion/255

"""#### Transform into one-hot encoding classes"""

y_train_fashion_binary = to_categorical(y_train_fashion)
y_test_fashion_binary = to_categorical(y_test_fashion)

"""#### Add an empty dimension to replace the RGB"""

print(x_train_fashion.shape)
x_train_fashion = x_train_fashion.reshape(x_train_fashion.shape[0],x_train_fashion.shape[1],x_train_fashion.shape[2],1)
print(x_train_fashion.shape)
x_test_fashion = x_test_fashion.reshape(x_test_fashion.shape[0],x_test_fashion.shape[1],x_test_fashion.shape[2],1)

"""### Base model trained on Fashion MNIST

#### Create a base model as done previously
"""

# Create input layer
input_shape = x_train_fashion.shape[1:]
input_layer = keras.layers.Input(input_shape)

# Create convolutive layer
hidden_conv_layer_1 = keras.layers.Conv2D(filters=16,
                                          kernel_size=(5,5) ,strides=1,
                                          padding='valid',activation='relu')(input_layer)
# create second convolutive layer
hidden_conv_layer_2 = keras.layers.Conv2D(filters=8,
                                          kernel_size=(5,5) ,strides=1,
                                          padding='valid')(hidden_conv_layer_1)

# add a batch normalization layer before activation
batch_norm_layer_2 = keras.layers.BatchNormalization(axis=-1)(hidden_conv_layer_2)

# add activation reread
activation_layer_2 = keras.layers.Activation('relu')(batch_norm_layer_2)

# flatten the image
flatenned_layer_2 = keras.layers.Flatten()(activation_layer_2)

nb_classes= len(np.unique(y_train))

# create the output layer
output_layer = keras.layers.Dense(units=nb_classes,activation='softmax')(flatenned_layer_2)

# create the model by linking the input to the output
model_fashion_mnist_bn = keras.models.Model(inputs=input_layer, outputs=output_layer)

# visualize the model built
model_fashion_mnist_bn.summary()

"""#### Pre-train the model on the Fashion MNIST dataset"""

# choose the optimization algorithm
optimizer_algo = keras.optimizers.SGD(learning_rate=0.1)

# cost function that we want to optimize
cost_function = keras.losses.categorical_crossentropy

# compil model
model_fashion_mnist_bn.compile(loss=cost_function,optimizer=optimizer_algo, metrics=['accuracy'])

# mini batch size and number of epochs
mini_batch_size = 32
nb_epochs = 200

percentage_of_train_as_validation = 0.2
history = model_fashion_mnist_bn.fit(x_train_fashion,y_train_fashion_binary,batch_size=mini_batch_size,
                    epochs=nb_epochs,verbose=False,
                    validation_split=percentage_of_train_as_validation)

history_dict = history.history
loss_train_epochs = history_dict['loss']
loss_val_epochs = history_dict['val_loss']

plt.figure()
plt.plot(loss_train_epochs,color='blue',label='train_loss')
plt.plot(loss_val_epochs,color='red',label='val_loss')
plt.xlabel('epoch')
plt.ylabel('loss')
plt.legend()
plt.savefig('epoch-loss.pdf')
plt.show()
plt.close()

"""#### Evaluate the model on Fashion_MNIST test set (just for information)"""

loss,acc = model_fashion_mnist_bn.evaluate(x_test_fashion,y_test_fashion_binary,verbose=False)

print("Accuracy on test :",acc)

"""### Transfer learning on the MNIST dataset

We first look at the performance of our new model on the MNIST dataset (remember that this model has never been trained on this dataset)
"""

loss,acc = model_fashion_mnist_bn.evaluate(x_test,y_test_binary,verbose=False)

print("Accuracy on test :",acc)

"""#### fine-tune the model on the new dataset (MNIST)"""

history = model_fashion_mnist_bn.fit(x_train,y_train_binary,batch_size = 32, epochs=200, validation_split = 0.2, verbose=False)

"""#### Trace the variation of the accuracy on the train and on the validation set according to the number of epochs"""

history_dict = history.history
acc_train_epochs = history_dict['loss']
acc_val_epochs = history_dict['val_accuracy']

plt.figure()
plt.plot(acc_train_epochs,color='blue',label='train_loss')
plt.plot(acc_val_epochs,color='red',label='val_loss')
plt.xlabel('epoch')
plt.ylabel('loss')
plt.legend()
plt.savefig('epoch-loss.pdf')
plt.show()
plt.close()

"""#### Evaluate the model on test set"""

loss,acc = model_fashion_mnist_bn.evaluate(x_test,y_test_binary,verbose=False)
print("Accuracy on test set is:",acc)

"""## **Exercice**

Train a model usgin regularization techniques on the Pokemon Images dataset
"""
df = pd.read_csv(os.path.join(os.path.dirname(__file__), "pokemon-stats-data.csv"))
df.head()


  
